services:
  - type: web
    name: extra-backend
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn extra.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
